name: Build React Native Android Release

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install React Native Dependencies
        working-directory: ./rnanjuman
        run: npm install

      - name: Build Android Release APK and AAB
        working-directory: ./rnanjuman/android
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: rnanjuman/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: rnanjuman/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload APK Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anjuman-shari-e-shian-apk
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

      - name: Upload AAB Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anjuman-shari-e-shian-aab
          path: ${{ steps.sign_aab.outputs.signedReleaseFile }}
