name: Build React Native Android Release

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install React Native Dependencies
        working-directory: ./rnanjuman
        run: npm install

      - name: Build Android Release APK and AAB
        working-directory: ./rnanjuman/android
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anjuman-shari-e-shian-apk
          path: rnanjuman/android/app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anjuman-shari-e-shian-aab
          path: rnanjuman/android/app/build/outputs/bundle/release/app-release.aab
